### ISSUE TITLE
Support for doc comments

### ISSUE THREAD

**Issue by niklasad1** [davidpdrsn/bae#5]
Hey, I can't find any support for doc comments is that intentional or something that you think is reasonable to support?

**Comment by davidpdrsn** [comment]
Can you give an example of what you'd like to do?

**Comment by niklasad1** [comment]
Sure, I have a proc macro for a trait such

```
/// maybe some docs here too
#[my_attr]
pub trait MyTrait {
   /// Returns h
  fn h(&self) -> String;
}
```

Thus, I would want to parse the doc comment on at least the trait methods.
With something like:

```rust
#[derive(Debug, Clone, FromAttributes)]
pub(crate) struct Method {
	pub name: syn::LitStr,
        // doc comments.
        // not sure what to name this but I think you get the point...
	pub doc: Option<syn::LitStr>,
}
```

**Comment by davidpdrsn** [comment]
Okay yeah that does make sense.

To me it feels slightly different from what `bae` does today. Currently it builds a little parser for a single attribute. So

```rust
#[derive(Debug, Clone, FromAttributes)]
pub(crate) struct Method {
	pub name: syn::LitStr,
}
```

Can find and parse things like `#[method(name = "foo")]`. Doc comments get turned into `#[doc = "your docs"]` which is a separate attribute. `Method` would now have to search for two attributes specifically `method` and `doc`.

Thats of course not impossible but feels slightly out of scope. Maybe writing your own handling of doc comments is better. What do you think?

**Comment by niklasad1** [comment]
Yeah, it makes sense to keep `bae` as clean and simple as it is I guess..

**Comment by davidpdrsn** [comment]
Thanks for understanding. I think I'll close this for now.
